In [2]:
import os
import sys
import json

from pathlib import Path
from dotenv import load_dotenv


path_proj = Path.cwd().parent
path_data = os.path.join(path_proj, "data")

load_dotenv()

sys.path.append(os.path.join(path_proj, "utils"))

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
neo4j_url = os.getenv("neo4jurl")
neo4j_user = os.getenv("noe4juser")
neo4j_password = os.getenv("neo4jpass")

In [4]:
from neo4j import GraphDatabase

with GraphDatabase.driver(neo4j_url, auth=(neo4j_user, neo4j_password)) as driver:
    driver.verify_connectivity()
    print("Successfully connected to Neo4j database")

Successfully connected to Neo4j database

In [5]:
driver = GraphDatabase.driver(neo4j_url, auth=(neo4j_user, neo4j_password))

with driver.session() as session:
    result = session.run("RETURN 1 AS number")
    record = result.single()
    print(f"Test query result: {record['number']}")

Test query result: 1

In [6]:
import pandas as pd
import ast

df_llm = pd.read_csv(os.path.join(path_data, "result_analysis.csv"))

df_llm["publication_date"] = pd.to_datetime(df_llm["publication_date"])
df_llm["embedding_signal"] = df_llm["embedding_signal"].apply(ast.literal_eval)

df_llm.head()

,url,title,publication_date,classification,score,signal,justification,evidence,embedding_signal
0,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,mostly_dovish,-0.5,Low job gains and a stabilizing unemployment r...,The labor market is no longer described as str...,"Job gains have remained low, and the unemploym...","[-0.039459228515625, -0.01479339599609375, -0...."
1,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,mostly_dovish,-0.5,Two FOMC members dissented in favor of an imme...,"The dissents provide a direct, though minority...","Stephen I. Miran and Christopher J. Waller, wh...","[0.010986328125, -0.03143310546875, -0.0175933..."
2,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,neutral,0.0,The Committee retained a data-dependent approa...,The statement does not pre-commit to either cu...,the Committee will carefully assess incoming d...,"[-0.0172576904296875, -0.0224761962890625, -0...."
3,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,neutral,0.0,The Committee emphasized two-sided risks aroun...,Attention to risks on both employment and infl...,The Committee is attentive to the risks to bot...,"[0.0009055137634277344, -0.0279388427734375, -..."
4,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,neutral,0.0,The Committee stated it could adjust policy in...,This is a general contingency statement rather...,prepared to adjust the stance of monetary poli...,"[-0.006946563720703125, -0.0029315948486328125..."

In [ ]:
df_llm.info()

<class 'pandas.DataFrame'>
RangeIndex: 1331 entries, 0 to 1330
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   url               1331 non-null   str
 1   title             1331 non-null   str
 2   publication_date  1331 non-null   datetime64[us]
 3   classification    1331 non-null   str
 4   score             1331 non-null   float64
 5   signal            1331 non-null   str
 6   justification     1331 non-null   str
 7   evidence          1331 non-null   str
 8   embedding_signal  1331 non-null   object
dtypes: datetime64[us](1), float64(1), object(1), str(6)
memory usage: 93.7+ KB

In [ ]:
for ind, row in df_llm.iterrows():
    query = """
       MERGE (p:Publication {url: $url})
       SET
            p.title = $title,
            p.publication_date = $publication_date
    """

    records, summary, keys = driver.execute_query(
        query,
        parameters_={
            "url": row["url"],
            "title": row["title"],
            "publication_date": row["publication_date"].to_pydatetime(),
        }
    )

    # query = """
    #     MERGE (d:Date {date: $publication_date})
    #     """
    # records, summary, keys = driver.execute_query(
    #     query,
    #     parameters_={
    #         "publication_date": row["publication_date"].to_pydatetime(),
    #     }
    # )

    # query = """
    #     MATCH (p:Publication {url: $url})
    #     MATCH (d:Date {date: $publication_date})
    #     MERGE (p)-[:PUBLISHED_ON]->(d)
    # """
    # records, summary, keys = driver.execute_query(
    #     query,
    #     parameters_={
    #         "url": row["url"],
    #         "publication_date": row["publication_date"].to_pydatetime(),
    #     }
    # )

    query = """
        MERGE (s:Signal {text: $signal,
                         url: $url})
        SET s.classification = $classification,
            s.score = $score,
            s.justification = $justification,
            s.evidence = $evidence,
            s.embedding_signal = $embedding_signal,
            s.date = $publication_date
    """
    records, summary, keys = driver.execute_query(
        query,
        parameters_={
            "signal": row["signal"],
            "url": row["url"],
            "classification": row["classification"],
            "score": row["score"],
            "justification": row["justification"],
            "evidence": row["evidence"],
            "embedding_signal": row["embedding_signal"],
            "publication_date": row["publication_date"].to_pydatetime(),
        }
    )

    query = """
        MATCH (p:Publication {url: $url})
        MATCH (s:Signal {text: $signal,
                         url: $url})
        MERGE (p)-[:HAS_SIGNAL]->(s)
    """
    records, summary, keys = driver.execute_query(
        query,
        parameters_={
            "url": row["url"],
            "signal": row["signal"],
        }
    )
    print(f"Processed record {ind} with URL: {row['url']}")

    if ind >= 200:
        break

Processed record 0 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 1 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 2 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 3 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 4 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 5 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 6 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 7 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 8 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 9 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128a.htm
Processed record 10 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 11 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 12 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 13 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 14 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 15 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 16 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 17 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 18 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 19 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 20 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 21 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 22 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 23 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 24 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 25 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 26 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 27 with URL: https://www.federalreserve.gov/monetarypolicy/fomcpressconf20260128.htm
Processed record 28 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128b.htm
Processed record 29 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128b.htm
Processed record 30 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128b.htm
Processed record 31 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128b.htm
Processed record 32 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20260128b.htm
Processed record 33 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 34 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 35 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 36 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 37 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 38 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 39 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 40 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 41 with URL: https://www.federalreserve.gov/newsevents/pressreleases/monetary20251210a.htm
Processed record 42 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 43 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 44 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 45 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 46 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 47 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 48 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 49 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm
Processed record 50 with URL: https://www.federalreserve.gov/monetarypolicy/fomcminutes20251210.htm

In [ ]:
query = """
CALL gds.graph.exists('signal-cypher')
YIELD exists
RETURN exists
"""
records, summary, keys = driver.execute_query(query)

if records[0]["exists"]:
    driver.execute_query("CALL gds.graph.drop('signal-cypher')")
    print("Dropped existing graph 'signal-cypher'")

query = """
MATCH (source:Signal)
WHERE source.embedding_signal IS NOT NULL
WITH gds.graph.project(
    'signal-cypher',
    source,
    null,
    {
        sourceNodeProperties: source {.embedding_signal},
        targetNodeProperties: null
    }
) as g
RETURN g.graphName AS graph, g.nodeCount AS nodes, g.relationshipCount AS rels
"""
records, summary, keys = driver.execute_query(query)
print(f"Created graph 'signal-cypher' with {records[0]['nodes']} nodes and {records[0]['rels']} relationships")

Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. `schema` returned by the procedure `gds.graph.drop` is deprecated.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL gds.graph.drop('signal-cypher')"

Dropped existing graph 'signal-cypher'
Created graph 'signal-cypher' with 81 nodes and 0 relationships

In [ ]:
query = """
CALL gds.knn.stream(
    'signal-cypher',
    {
        nodeProperties: [
            {embedding_signal: 'COSINE'}
            ],
        similarityCutoff: 0.75,
        topK: 50,
        randomSeed: 42,
        concurrency: 1

    }
)
YIELD node1, node2, similarity
WITH
    gds.util.asNode(node1) AS n1,
    gds.util.asNode(node2) AS n2,
    similarity
WHERE elementId(n1) < elementId(n2)
MERGE (n1)-[r:SIMILAR_TO]-(n2)
SET r.score = similarity
RETURN count(r) AS total_score_relationships
"""
records, summary, keys = driver.execute_query(query)
print(f"{records[0]['total_score_relationships']} relationships")

368 relationships

In [ ]:
df_llm.head()

,url,title,publication_date,classification,score,signal,justification,evidence,embedding_signal
0,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,dovish,-1.0,Two FOMC voters dissented in favor of a 25 bas...,A preference by dissenting members to lower th...,Voting against this action were Stephen I. Mir...,"[0.0205841064453125, -0.025970458984375, -0.01..."
1,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,mostly_dovish,-0.5,Job gains have remained low and unemployment h...,"Low job gains point to labor market softening,...","Job gains have remained low, and the unemploym...","[0.01035308837890625, -0.0050811767578125, -0...."
2,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,neutral,0.0,The Committee maintained the federal funds rat...,Holding rates steady does not by itself indica...,the Committee decided to maintain the target r...,"[0.0186309814453125, 0.00258636474609375, -0.0..."
3,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,neutral,0.0,"The Committee will assess incoming data, the e...",This data-dependent guidance leaves open both ...,"will carefully assess incoming data, the evolv...","[-0.0210113525390625, 0.00955963134765625, -0...."
4,https://www.federalreserve.gov/newsevents/pres...,Federal Reserve issues FOMC statement,2026-01-28,neutral,0.0,The Committee is attentive to risks on both si...,Balanced-risk language does not indicate a dom...,The Committee is attentive to the risks to bot...,"[-0.0092010498046875, -0.028900146484375, -0.0..."

In [ ]:
records, summary, keys = driver.execute_query("""
    MATCH (p:Person)-[:KNOWS]->(:Person)
    RETURN p.name AS name
    """,
    database_="<database-name>",
)

ClientError: {neo4j_code: Neo.ClientError.Database.DatabaseNotFound} {message: Unable to get a routing table for database '<database-name>' because this database does not exist} {gql_status: 22000} {gql_status_description: error: data exception}